apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
data:
  azurestorageaccountname: aGVsbG93b3JsZG1vbmdvZGJzdG9yYWdl
  azurestorageaccountkey: eXJURDUzMVYzNWhORjFBZGRka2w5Q2lDa0Rjdy85akx4aGVGWG5FRlozY3MybTVVNFE2OFNpYlIzMjNhR2JpTEJnTFV5OXRSYXlITWtBRnFMMTM0SVE9PQ==