apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: helloworld-azure-data-pvol-claim
    type: local
  name: helloworld-azure-data-pvol-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""