apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose.yml
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: helloworldspa
  name: helloworldspa
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: helloworldspa
    spec:
      containers:
      - args:
        - nginx-debug
        - -g
        - daemon off;
        env:
        - name: NODE_ENV
          value: production
        #image: shailensukul/shailen:helloworldspagoogle
        image: shailensukul/shailen:helloworldspaazure
        name: helloworldspa
        ports:
        - containerPort: 80
        resources: {}
        imagePullPolicy: Always # added manually
        stdin: true
        tty: true
      restartPolicy: Always
status: {}
