apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose.yml
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: helloworldapi
  name: helloworldapi
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: helloworldapi
    spec:
      containers:
      - image: shailensukul/shailen:helloworldapi
        name: helloworldapi
        ports:
        - containerPort: 443
        - containerPort: 80
        resources: {}
        imagePullPolicy: Always # added manually
        # stdin: true
        # tty: true
      restartPolicy: Always
status: {}
