apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f docker-compose.yml
    kompose.version: 1.10.0 (8bb0907)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
      - args:
        - --smallfiles
        image: mongo:latest
        name: mongodb
        ports:
        - containerPort: 27017
        resources: {}
        imagePullPolicy: Always # added manually
        volumeMounts:
        - mountPath: /data/db
          name: hellowworld-data-vol
      restartPolicy: Always
      volumes:
      - name: hellowworld-data-vol
        azureFile:
          secretName: azure-secret
          shareName: mongoshare
          readOnly: false
status: {}
